---

- name: Restart supervisord program
  supervisorctl:
    name: lounge
    state: restarted
  become: yes

- name: List all npm temporary files
  find:
    paths: /tmp/
    patterns: "npm-*"
  register: npm_temporary_files

- name: Clean up npm temporary files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ npm_temporary_files.files }}"
  become: yes
